### ISSUE TITLE
Error parsing date

### ISSUE THREAD

**Issue by xjmzx** [dtonon/stacker-beep#1]
I tried both compiling with `go build -o stacker-beep -ldflags="-s -w" .`
and using the binary directly, but getting an error. The output is:

```
Error parsing date: parsing time "" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "2006"
Error parsing date: parsing time "" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "2006"
Error parsing date: parsing time "" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "2006"
...
```

Not sure whether it would eventually resolve or not.
Could also be a problem with my system

Debian GNU/Linux 12 (bookworm) x86_64
go version go1.22.0 linux/amd64

**Comment by dtonon** [comment]
I will check, thanks for reporting

**Comment by dtonon** [comment]
@xjmzx sorry for the huge delay, fixed in 3a96911.

**Comment by xjmzx** [comment]
Oddly I'm still getting the same error despite reinstalling/upgrading go, pulling from repo and reinstalling.

**Comment by dtonon** [comment]
Weird, the update is really trivial, it's just a date parsing fix, No need to upgrade go.
Are you sure you pulled the last commit and run/compiled it?
